name: GitHub Actions Demo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Snyk_SCA_Test:
    runs-on: ubuntu-latest
    container:
      image: gradle:7.3.3-jdk17
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects
          
  Snyk_SAST_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master   
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --code 
        continue-on-error: true
        
      - run: npm install snyk-to-html -g
    
      - name: Generating json with results
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --code --json > results.json
        continue-on-error: true
          
      - name: Convert Snyk Json to html report
        run: snyk-to-html -i results.json -o results.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Upload Snyk Results Artifact
        uses: actions/upload-artifact@master
        with:
          name: results.html
          path: results.html

  Snyk_IaC_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd app
          yarn
          yarn build
          npm install -g cdk snyk
          cdk synth
          snyk iac test cdk.out/*.json
      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/gradle-jdk17@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --iac     